            Basics of Tensorflow

In [3]:
import tensorflow as tf

In [4]:
tf.constant([
    [1.0,2.0,3.0],
    [4.0,5.0,6.0]
])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [5]:
tf.constant([
    [1,2,3],
    [4,5,6]
])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
tf.constant(90)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [7]:
tf.constant([1,2,3,4,5,6,7,8,9,10])

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [8]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [9]:
tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float16)

<tf.Tensor: shape=(6,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float16)>

In [11]:
tf.constant(0, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [15]:
tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
tf.constant([1, 2, 3, 4, 5, 6], shape=[3, 2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [16]:
t = tf.constant([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

In [17]:
t.dtype

tf.float32

In [18]:
t.shape

TensorShape([2, 3])

In [19]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [20]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [21]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [22]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [23]:
tf.sqrt(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>

In [24]:
tf.abs(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [27]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [28]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [30]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [29]:
tf.add(t, 10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [32]:
tf.subtract(t, 2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]], dtype=float32)>

In [33]:
tf.multiply(t, 4)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [16., 20., 24.]], dtype=float32)>

In [37]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [41]:
# Type Conversions

t2 = tf.constant(40, dtype=tf.float64)
tf.constant(2.0, dtype=tf.float16) + tf.cast(t2, tf.float16)

<tf.Tensor: shape=(), dtype=float16, numpy=42.0>

In [45]:
# variables

v = tf.Variable([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [46]:
# to change the individual cells

v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [47]:
v[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [48]:
v[1,0].assign(900)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  2.,  42.,   6.],
       [900.,  10.,  12.]], dtype=float32)>

In [49]:
v[:, 2].assign([0.0, 1.0])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  2.,  42.,   0.],
       [900.,  10.,   1.]], dtype=float32)>

In [50]:
v[:, 1].assign([12.9, 9.7])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  2. ,  12.9,   0. ],
       [900. ,   9.7,   1. ]], dtype=float32)>

In [52]:
# changing at once multiple cells and slices

v.scatter_nd_update(
    indices=[[0,0],[1,2]],
    updates=[100.0, 200.0]
)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100. ,  12.9,   0. ],
       [900. ,   9.7, 200. ]], dtype=float32)>